### ISSUE TITLE
how to rotate video ? [SOLVED]

### ISSUE THREAD

**Issue by zoldaten** [miroslavpejic85/mirotalkc2c#11]
as i have camera 90 output i have to rotate video output.
at start i think of using another js script to access html element by id and change it:
```
 // Access DOM element object
const rotated = document.getElementById('rotated');
// Rotate element by 90 degrees clockwise
rotated.style.transform = 'rotate(90deg)';
```

but it doesnt work.

later i found the solution. 
just need to add 
`transform: rotate(90deg);`
to
`/home/pi/mirotalkc2c/frontend/css/client.css`
in section:
```
.myVideoWrap {
    position: absolute;
    transform: rotate(90deg);
    z-index: 5;
    top: 10px;
    left: 10px;
    width: var(--my-video-wrap-width);
    height: var(--my-video-wrap-height);
    border: var(--border);
    border-radius: var(--border-radius);
}
```

here we are!
![Screenshot_1](https://github.com/miroslavpejic85/mirotalkc2c/assets/29411817/c626887a-6562-499d-a46c-80d858e941e3)

**Comment by miroslavpejic85** [comment]
Hello @zoldaten,

I've added a rotate button to the video header, allowing users to freely adjust the orientation in case they encounter camera-related issues, similar to your experience.

![mirotalk-c2c-rotate-button](https://github.com/miroslavpejic85/mirotalkc2c/assets/70838434/feb7634d-911a-47c7-b8f1-204b74878b3c)

Thank you and have a great day!

**Comment by zoldaten** [comment]
thanks! 
but i have to start headless so need it at start up.
by the way how to transponse video horizontally as i see it mirrored ?

**Comment by miroslavpejic85** [comment]
We're discussing the flexibility to customize the code to fit your specific needs. Feel free to adapt the code as you see fit. If you have any questions or need assistance with anything in the future, please join our forum [here](https://discord.gg/rgGYfeYW3N). It's a great place to engage with our community. Thank you!
