### ISSUE TITLE
Feature Request - Version Stamp .env_template

### ISSUE THREAD

**Issue by brackenhill-mob** [miroslavpejic85/mirotalkc2c#14]
Makes it easier to work out when we need to update our working .env.

At the moment, I diff my working .env and the new .env_template each time I pull a new version which takes time as my working file is heavily modified with other stuff for my integration setup.

This would also apply to P2P and SFU's app/src/config.template.js

**Comment by miroslavpejic85** [comment]
Typically, these files undergo minimal modifications, with rare updates. In the event of any changes, I will promptly notify the relevant channel in the forum through an [announcement](https://discord.gg/8BJbn6wjUy) in the [official forum](https://discord.gg/rgGYfeYW3N).
