### ISSUE TITLE
Iframe available options

### ISSUE THREAD

**Issue by pragmatech** [miroslavpejic85/mirotalkc2c#2]
Using the iframe so that the user drops into a preset room name would be useful. Currently it seems that one must include a username in such a preset url in the iframe, which isn't ideal. Any pointers or approach to how one does this is appreciated.
mahalo from Mauna Loa

**Comment by miroslavpejic85** [comment]
Based of you needs, you can create 3 type of Iframes for a website:

1. Set the `Room` and `Username` desired: https://c2c.mirotalk.com

```html
<iframe
    allow="camera; microphone; display-capture; fullscreen; clipboard-read; clipboard-write; web-share; autoplay"
    src="https://c2c.mirotalk.com"
    style="height: 100vh; width: 100vw; border: 0px;"
></iframe>
```

2. Set the `Username` desired: https://c2c.mirotalk.com/?room=test

```html
<iframe
    allow="camera; microphone; display-capture; fullscreen; clipboard-read; clipboard-write; web-share; autoplay"
    src="https://c2c.mirotalk.com/?room=test"
    style="height: 100vh; width: 100vw; border: 0px;"
></iframe>
```

3. `Direct Join`: https://c2c.mirotalk.com/join?room=test&name=test

```html
<iframe
    allow="camera; microphone; display-capture; fullscreen; clipboard-read; clipboard-write; web-share; autoplay"
    src="https://c2c.mirotalk.com/join?room=test&name=test"
    style="height: 100vh; width: 100vw; border: 0px;"
></iframe>
```

**Comment by pragmatech** [comment]
> <iframe
>     allow="camera; microphone; fullscreen; display-capture; autoplay"
>     src="https://c2c.mirotalk.com/?room=test"
>     style="height: 100%; width: 100%; border: 0px;"
> ></iframe>

It seems that the above setting (and what is preferrable in my use case) does not allow for the client to load. 
(whereas if some arbitrary user name is included ala 'Direct Join' it loads, but with that somewhat odd chosen name string.)

**Comment by miroslavpejic85** [comment]
> It seems that the above setting (and what is preferrable in my use case) does not allow for the client to load.

Here the user need to `set a Username` if not already done before (that is saved on localStorage), then click `JOIN` button to join the room (2), It's different then Direct Join (3) where you can change the src any time with the room and name desired from your website. You can handle iframes at will from your site's code...(iframe src are not static, the 3 mentioned above are examples of use). So if you need something different, adapt it for your needs.

**Comment by pragmatech** [comment]
> if not already done before (that is saved on localStorage), then click JOIN button to join the room (2)

Indeed, I may need to get clear on my end, dev wise. 
Not to belabor the issue (well to belabor it actually), the click JOIN, under (2) yields:
{"data":"404 not found"}

**Comment by miroslavpejic85** [comment]
Make sure you entered the `SRC` correctly in the iframe.

![join](https://user-images.githubusercontent.com/70838434/206382293-3223ddb8-2b5e-411b-8de8-bde248e30672.gif)

Please, for future questions, discussions and so on, join with us on [Discord](https://discord.gg/rgGYfeYW3N) and not open issues here, which are usually for reporting bugs. 

Thank you for understanding.

**Comment by surya-ttec** [comment]
after embedding into my website from iframe option 3 , I am having issues with audio in the recording file, sometimes its missing the other user voice , how can we fix this? is it mic issue? , but audio is fine when both users are in talk .
