### ISSUE TITLE
function roomIsBusy

### ISSUE THREAD

**Issue by pragmatech** [miroslavpejic85/mirotalkc2c#3]
I assume that tweaking (roomPeersCount > 2) to any number that may perform acceptably (my use-case might be audio-only mesh, which would seem to perform well enough for up to at least 8?) 
Still, I'm wondering what value was being considered when this governer was coded in. Could be insightful. thanks

**Comment by miroslavpejic85** [comment]
Hi @pragmatech,

The code is designed (intentionally) to handle even 2+ peers if desired, but for the purpose of the project it is limited to cam-2-cam. 

Please, for future questions, discussions and so on, join with us on [Discord](https://discord.gg/rgGYfeYW3N) and not open issues here, which are usually for reporting bugs. 

Thank you for understanding.
