### ISSUE TITLE
About encryption

### ISSUE THREAD

**Issue by Iridesscent233** [miroslavpejic85/mirotalkc2c#4]
What encryption method is used for end-to-end encryption? In which file?

**Comment by miroslavpejic85** [comment]
Hello @Iridesscent233,

`Encryption` is a mandatory feature of `WebRTC`, and is enforced on all components in `MiroTalk C2C`. Resultantly, all media streams sent over WebRTC are securely encrypted, enacted through standardised and well-known `encryption protocols`. The encryption protocol used depends on the channel type, `data` streams are encrypted using `Datagram Transport Layer Security` ([DTLS](https://en.wikipedia.org/wiki/Datagram_Transport_Layer_Security)) and `media` streams are encrypted using `Secure Real-time Transport Protocol` ([SRTP](https://en.wikipedia.org/wiki/Secure_Real-time_Transport_Protocol)). 

Please, for `questions, discussions and supports`, join with us on [Discord](https://discord.gg/rgGYfeYW3N) 
Here you can find many answers about it and interact with the community.

Thank you and have a good weekend!

**Comment by Iridesscent233** [comment]
Can I set the key myself?
