### ISSUE TITLE
RFE: configurable video resolution and framerate

### ISSUE THREAD

**Issue by mlichvar** [miroslavpejic85/mirotalkc2c#6]
It seems the default video constraints are 1280x720@30 and there is an option to set 3840x2160@60. Some computers are too noisy even when encoding at 1280x720 (e.g. firefox not using HW acceleration). It would be nice if the resolution and framerate could be set directly in the UI.

**Comment by miroslavpejic85** [comment]
Hello @mlichvar,

I will explain you better the current logic:

```js
    if (config.forceToMaxVideoAndFps) {
        videoConstraints = {
            width: { ideal: 3840 },
            height: { ideal: 2160 },
            frameRate: { ideal: 60 },
        };
    } else {
        videoConstraints = {
            width: { ideal: 1280 },
            height: { ideal: 720 },
            frameRate: { ideal: 30 },
        };
    }
```

`1280 x 720 and 30fps` as the default and the `ideal one`. That means, if your webcam or screen support this default resolution - fps, it will be set, if not, it takes the supported one started from 320x240, it can be 640x480 15fps and so on, up max to 1280 x 720 and 30 fps.

`3840 x 2160 and 60fps` if enabled is the `ideal one`. The same logic, if you have a webcam or screen with 4k resolution and support 60fps, it will be set, if not, the maximum that the webcam or screen support, that start from 320x240 up to 3840 x 2160 and 60fps. For example, for the webcam or screen 2k - 30fps MiroTalk will set 2560 x 1440 - 30fps.

I can add the option to set video resolution and fps in the settings, as in other MiroTalk versions, but here, as `Cam 2 Cam`, with the current logic i described before, it `ensuring an optimal video resolution and fps`. 

Thank you.

**Comment by miroslavpejic85** [comment]
Done, now you can set also the `video quality` and `fps` in the settings or use the `Best quality` functionality described before.

<img width="1142" alt="mirotalk-c2c-video-quality-fps" src="https://github.com/miroslavpejic85/mirotalkc2c/assets/70838434/f0da9e03-d916-4447-8e02-b233a1c91a51">

**Comment by mlichvar** [comment]
This is great. Thanks!
